function getMatches(listing) {
  const buyers = [
    { buyer_id: 'buyer-retail-1', buyer_name: 'Kovai Fresh Mart', buyer_type: 'retailer', distance_km: 14, requested_kg: 800, offered_price: 27, price_min: 25, price_max: 29, phone: '+919842111001', email: 'procurement@kovaifresh.in', delivery_location: 'Gandhipuram, Coimbatore', delivery_window: 'Tomorrow morning 6–9 AM', freshness_required: 'Harvested within 24 hours', quality_required: 'Premium / Grade A', agmark_required: 'Preferred' },
    { buyer_id: 'buyer-hotel-1', buyer_name: 'Kovai Annapoorna Hotel Chain', buyer_type: 'restaurant', distance_km: 22, requested_kg: 500, offered_price: 28, price_min: 26, price_max: 30, phone: '+919842111002', email: 'kitchen@annapoorna.in', delivery_location: 'RS Puram Central Kitchen, Coimbatore', delivery_window: 'Daily morning batch', freshness_required: 'Fresh daily harvest', quality_required: 'Grade A', agmark_required: 'Preferred' },
    { buyer_id: 'buyer-fpo-1', buyer_name: 'Reliance Fresh Regional Distribution Hub', buyer_type: 'institution', distance_km: 35, requested_kg: 2500, offered_price: 26, price_min: 24, price_max: 28, phone: '+919842111003', email: 'agri-procurement@reliancefresh.in', delivery_location: 'Perundurai Logistics Park, Erode', delivery_window: 'Within 48 hours', freshness_required: 'Grade A farmgate produce', quality_required: 'Grade A / AGMARK', agmark_required: 'Mandatory' },
    { buyer_id: 'buyer-super-1', buyer_name: 'Subam Supermarket Hub', buyer_type: 'retailer', distance_km: 41, requested_kg: 600, offered_price: 34, price_min: 30, price_max: 36, phone: '+919842111004', email: 'orders@subamsuper.in', delivery_location: 'Salem Town Depot', delivery_window: 'This weekend', freshness_required: 'Fresh hill harvest', quality_required: 'Grade A', agmark_required: 'Not mandatory' },
    { buyer_id: 'buyer-mandi-1', buyer_name: 'Oddanchatram Wholesale Vegetable Commission Mandi', buyer_type: 'wholesaler', distance_km: 55, requested_kg: 4000, offered_price: 24, price_min: 22, price_max: 26, phone: '+919842111005', email: 'mandi@oddanchatramtraders.in', delivery_location: 'Oddanchatram Central Market Yard', delivery_window: 'Immediate dispatch', freshness_required: 'Bulk daily arrivals', quality_required: 'Grade A or B', agmark_required: 'Optional' }
  ];
  return buyers.map((buyer, index) => ({ ...buyer, listing_id: listing.id, crop: listing.crop, requirement: `Need ${listing.crop} for ${buyer.buyer_type} supply`, rank: index + 1, match_score: 94 - index * 7, status: index === 0 ? 'active' : 'interest' }));
}
function buyerRequirements() { return getMatches({ id: 'open-requirements', crop: 'fresh vegetables' }); }
module.exports = { getMatches, buyerRequirements };
