const dialog=document.querySelector('#auth-dialog');
const panels={login:document.querySelector('#login-panel'),register:document.querySelector('#register-panel')};
const dashboard=document.querySelector('#dashboard-page');
const currency=value=>`₹${Number(value||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
const api=async(path,options={})=>{const token=localStorage.getItem('uyirva_access_token');const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});const data=await response.json();if(!response.ok)throw new Error(data.detail||'Request failed.');return data};

function openAuth(view){panels.login.hidden=view!=='login';panels.register.hidden=view!=='register';dialog.showModal();panels[view].querySelector('input').focus()}
document.querySelectorAll('[data-open-auth]').forEach(button=>button.addEventListener('click',()=>openAuth(button.dataset.openAuth)));
document.querySelector('#close-auth').addEventListener('click',()=>dialog.close());

async function showDashboard(user){const role=user.role.toUpperCase();if(!['FARMER','BUYER','FPO'].includes(role))return;document.querySelector('#landing-page').hidden=true;document.querySelector('.site-header').hidden=true;dashboard.hidden=false;dashboard.innerHTML=`<header><div><p class="eyebrow">UYIRVA · ${role}</p><h1>${role==='BUYER'?'Buyer dashboard':role==='FARMER'?'Farmer dashboard':'FPO dashboard'}</h1><p class="muted">Welcome, ${user.full_name}. Your marketplace overview is ready.</p></div><button class="button button-secondary" id="logout">Sign out</button></header><p class="form-message" id="dashboard-message" aria-live="polite"></p><section id="dashboard-content"></section>`;document.querySelector('#logout').addEventListener('click',()=>{localStorage.clear();location.replace('/')});try{if(role==='BUYER')await renderBuyerDashboard();else if(role==='FARMER')await renderFarmerDashboard();else document.querySelector('#dashboard-content').innerHTML='<article><h3>FPO tools</h3><p>Collective trading tools are coming next.</p></article>'}catch(error){document.querySelector('#dashboard-message').textContent=error.message}}

async function renderBuyerDashboard(){const data=await api('/api/buyer/dashboard');const demands=data.demands||[];const matches=data.matches||[];document.querySelector('#dashboard-content').innerHTML=`<div class="dashboard-actions"><button class="button button-primary" id="new-demand">Create demand request</button></div><div class="card-grid"><article><h3>Open demands</h3><div class="stat">${demands.length}</div><p>Your active crop requests.</p></article><article><h3>Supplier matches</h3><div class="stat">${matches.reduce((total,match)=>total+match.farmer_count,0)}</div><p>Farmers matched to your requests.</p></article><article><h3>Route savings</h3><div class="stat">${data.pooled_orders.route_savings_km} km</div><p>${data.pooled_orders.cost_reduction} estimated saving.</p></article></div><section class="dashboard-section"><h2>Demand requests</h2>${demands.length?`<div class="record-list">${demands.map(d=>`<article><h3>${d.crop_name}</h3><p>${d.quantity_kg} kg · Target ${currency(d.target_price)}/kg</p><p class="muted">${d.status}</p></article>`).join('')}</div>`:'<p class="muted">No open demand requests yet.</p>'}</section><section class="dashboard-section"><h2>Smart matches</h2>${matches.length?`<div class="record-list">${matches.map(m=>`<article><h3>${m.crop_name} · ${m.match_score}% match</h3><p>${m.farmer_count} farmer${m.farmer_count===1?'':'s'} can supply ${m.total_available_kg} kg for your ${m.demand_quantity} kg request.</p></article>`).join('')}</div>`:'<p class="muted">Create a demand request to find compatible farmer listings.</p>'}</section>`;document.querySelector('#new-demand').addEventListener('click',showDemandForm)}
function showDemandForm(){document.querySelector('#dashboard-content').insertAdjacentHTML('afterbegin',`<form class="trade-form" id="demand-form"><h2>Create demand request</h2><label>Crop<input name="crop_name" required maxlength="100" placeholder="e.g. Tomato"></label><label>Quantity (kg)<input name="quantity_kg" type="number" min="1" step="0.01" required></label><label>Target price (₹/kg)<input name="target_price" type="number" min="0.01" step="0.01" required></label><div class="actions"><button class="button button-primary" type="submit">Find farmers</button><button class="button button-secondary" type="button" id="cancel-demand">Cancel</button></div></form>`);document.querySelector('#new-demand').disabled=true;document.querySelector('#cancel-demand').addEventListener('click',renderBuyerDashboard);document.querySelector('#demand-form').addEventListener('submit',submitDemand)}
async function submitDemand(event){event.preventDefault();const form=event.currentTarget;const submit=form.querySelector('[type=submit]');submit.disabled=true;try{const data=await api('/api/buyer/demands',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});await renderBuyerDashboard();document.querySelector('#dashboard-message').textContent=`Demand created. ${data.matches_found} compatible farmer match${data.matches_found===1?'':'es'} found.`}catch(error){document.querySelector('#dashboard-message').textContent=error.message}finally{submit.disabled=false}}

async function renderFarmerDashboard(){const data=await api('/api/farmer/dashboard');const listings=data.listings||[];document.querySelector('#dashboard-content').innerHTML=`<div class="dashboard-actions"><button class="button button-primary" id="new-listing">Create listing</button></div><div class="card-grid"><article><h3>Active listings</h3><div class="stat">${listings.length}</div><p>Produce available to buyers.</p></article><article><h3>Expected settlement</h3><div class="stat">${currency(data.payout_expected)}</div><p>Across active listings.</p></article><article><h3>Demand signal</h3><div class="stat">${data.demand_indicator.status}</div><p>${data.demand_indicator.crop}</p></article></div><section class="dashboard-section"><h2>Your listings</h2>${listings.length?`<div class="record-list">${listings.map(l=>`<article><h3>${l.crop_name}</h3><p>${l.quantity_kg} kg · ${currency(l.expected_price)}/kg</p><p class="muted">${l.ai_quality_score} · ${l.ai_price_recommendation}</p></article>`).join('')}</div>`:'<p class="muted">No active listings yet.</p>'}</section>`;document.querySelector('#new-listing').addEventListener('click',showListingForm)}
function showListingForm(){document.querySelector('#dashboard-content').insertAdjacentHTML('afterbegin',`<form class="trade-form" id="listing-form"><h2>Create crop listing</h2><label>Crop<input name="crop_name" required maxlength="100" placeholder="e.g. Tomato"></label><label>Quantity (kg)<input name="quantity_kg" type="number" min="1" step="0.01" required></label><label>Expected price (₹/kg)<input name="expected_price" type="number" min="0.01" step="0.01" required></label><div class="actions"><button class="button button-primary" type="submit">Publish listing</button><button class="button button-secondary" type="button" id="cancel-listing">Cancel</button></div></form>`);document.querySelector('#new-listing').disabled=true;document.querySelector('#cancel-listing').addEventListener('click',renderFarmerDashboard);document.querySelector('#listing-form').addEventListener('submit',submitListing)}
async function submitListing(event){event.preventDefault();const form=event.currentTarget;const submit=form.querySelector('[type=submit]');submit.disabled=true;try{await api('/api/farmer/listings',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});await renderFarmerDashboard();document.querySelector('#dashboard-message').textContent='Listing published successfully.'}catch(error){document.querySelector('#dashboard-message').textContent=error.message}finally{submit.disabled=false}}

async function authenticate(form,path){const message=form.querySelector('.form-message');const submit=form.querySelector('[type=submit]');const payload=Object.fromEntries(new FormData(form));message.textContent='';submit.disabled=true;try{const response=await fetch(`/api/auth/${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.detail||'Unable to complete your request.');localStorage.setItem('uyirva_access_token',data.access_token);const user=await api('/api/auth/me');localStorage.setItem('uyirva_user',JSON.stringify(user));dialog.close();await showDashboard(user)}catch(error){message.textContent=error.message}finally{submit.disabled=false}}
document.querySelector('#login-form').addEventListener('submit',event=>{event.preventDefault();authenticate(event.currentTarget,'login')});
document.querySelector('#register-form').addEventListener('submit',event=>{event.preventDefault();authenticate(event.currentTarget,'register')});
const saved=JSON.parse(localStorage.getItem('uyirva_user')||'null');if(saved)showDashboard(saved);
