const user = JSON.parse(localStorage.getItem('uyirva_user') || 'null');
const token = localStorage.getItem('uyirva_access_token');
const demoMode = localStorage.getItem('uyirva_demo_mode') === 'true';
const app = document.querySelector('#dashboard-app');
const apiBase = window.UYIRVA_API_URL || window.location.origin;
const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));

if (!user || (!token && !demoMode)) location.assign('index.html');
else {
  const role = String(user.role).toLowerCase();
  const api = async (path, options = {}) => { const response = await fetch(`${apiBase}${path}`, { ...options, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}`, ...options.headers } }); const data = await response.json(); if (!response.ok) { if (response.status === 401) { localStorage.clear(); location.assign('index.html'); return new Promise(() => {}); } throw new Error(data.detail || 'Request failed'); } return data; };
  const logout = () => { localStorage.clear(); location.assign('index.html'); };
  const shell = (title, content) => { app.innerHTML = `<div class="dashboard-top"><div><div class="eyebrow">UYIRVA · ${role.toUpperCase()}</div><h1>${title}</h1><p>Your marketplace workspace.</p></div><button class="button logout-button" id="logout">Sign out</button></div>${content}`; document.querySelector('#logout').onclick = logout; };
  const listingCard = item => `<div class="listing-item">${item.photo_url ? `<img src="${item.photo_url}" alt="${escapeHtml(item.crop)}">` : ''}<div><b>${escapeHtml(item.crop)}</b><p>${item.quantity} kg · ₹${item.price}/kg</p><small>${escapeHtml(item.freshness || '')} · ${escapeHtml(item.quality_grade || '')}</small></div></div>`;
  const buyerCard = buyer => `<div class="buyer-requirement"><b>${escapeHtml(buyer.buyer_name)}</b><span>${escapeHtml(buyer.buyer_type)} · ${buyer.distance_km} km</span><p>Needs ${buyer.quantity} kg of ${escapeHtml(buyer.crop)} · ₹${buyer.price_min}–₹${buyer.price_max}/kg</p><small>Delivery: ${escapeHtml(buyer.delivery_location)} · ${escapeHtml(buyer.delivery_window)}</small><p>${buyer.contact_visible ? `Contact: ${escapeHtml(buyer.contact.phone)} · ${escapeHtml(buyer.contact.email)}` : 'Contact details are private until this interest is an active match or order.'}</p><button class="button secondary" data-chat="${buyer.match_id}">Open negotiation</button></div>`;
  const orderCard = order => `<div class="order-item"><b>${escapeHtml(order.buyer_name)}</b><p>${escapeHtml(order.crop)} · ${order.quantity} kg · Agreed ₹${order.agreed_price}/kg</p><small>Accepted → Pooled → Dispatched → Delivered → Paid</small><p>Current: ${escapeHtml(order.order_status)} · Escrow: ${escapeHtml(order.escrow_status)}</p>${order.logistics ? `<p><b>Driver:</b> ${escapeHtml(order.logistics.driver_name)} · ${escapeHtml(order.logistics.contact_number)}<br><b>Vehicle:</b> ${escapeHtml(order.logistics.vehicle_number)} · Pickup: ${escapeHtml(order.logistics.pickup_time_window)}</p>` : '<p>Logistics: pending assignment</p>'}</div>`;
  const bindChats = () => document.querySelectorAll('[data-chat]').forEach(button => button.onclick = async () => { const text = window.prompt('Send a message to this buyer'); if (text?.trim()) { try { await api(`/api/farmer/matches/${button.dataset.chat}/messages`, { method: 'POST', body: JSON.stringify({ text }) }); window.alert('Message sent.'); } catch (error) { window.alert(error.message); } } });

  async function farmer() {
    const [data, listingData, buyersData, acceptedData] = await Promise.all([api('/api/farmer/dashboard'), api('/api/farmer/listings'), api('/api/farmer/buyers?sort=distance'), api('/api/farmer/accepted-orders')]);
    shell('Farmer Home', `<div class="feature-grid"><div class="feature-card"><h3>My vegetable listings</h3><strong>${data.stats.active_listings}</strong><p>Active listings · Pending orders: ${data.stats.pending_orders}</p><button class="button primary" id="create">List vegetables</button></div><div class="feature-card"><h3>Action needed</h3><p>${data.actions.unread_matches} buyer matches · ${data.actions.disputes_awaiting_response} disputes</p></div><div class="feature-card"><h3>Demand planning</h3><p>${escapeHtml(data.demand_insight.recommendation)}</p></div><div class="feature-card"><h3>This month earnings</h3><strong>₹${data.stats.month_earnings}</strong></div></div><div class="feature-card"><h3>My listed vegetables</h3><div class="listing-list">${listingData.listings.length ? listingData.listings.map(listingCard).join('') : '<p>No vegetables listed yet. Create a listing to reach buyers.</p>'}</div></div><div class="feature-card"><h3>Buyers</h3><p class="buyer-note">Matched buyers and buyers interested in your active listings.</p><div class="buyer-requirements">${buyersData.buyers.length ? buyersData.buyers.map(buyerCard).join('') : '<p>No buyer interest yet.</p>'}</div></div><div class="feature-card"><h3>Accepted orders</h3><div class="order-list">${acceptedData.orders.length ? acceptedData.orders.map(orderCard).join('') : '<p>No buyer-confirmed orders yet.</p>'}</div></div>`);
    document.querySelector('#create').onclick = () => document.querySelector('#listing-modal').classList.add('open'); bindChats();
  }
  function farmerDemo() { shell('Farmer Demo Dashboard', '<div class="feature-card"><h3>Demo mode</h3><p>Sign in with OTP to view live buyers, orders, and logistics.</p></div>'); }
  async function buyer() { const data = await api('/api/buyer/dashboard'); shell('Buyer Home', `<div class="feature-card"><h3>Active orders</h3><strong>${data.stats.active_orders}</strong></div>`); }
  async function logistics() { const data = await api('/api/logistics/orders'); shell('Logistics Partner', `<div class="feature-card"><h3>Assigned orders</h3><strong>${data.orders.length}</strong></div>`); }
  async function admin() { const data = await api('/api/admin/dashboard'); shell('Admin Control Centre', `<div class="feature-card"><h3>Adoption rate</h3><strong>${data.analytics.adoption_rate}%</strong></div>`); }
  if (demoMode) farmerDemo(); else ({ farmer, buyer, logistics, admin }[role] || (() => shell('Dashboard', 'Unsupported role.')))().catch(error => shell('Dashboard error', `<p>${escapeHtml(error.message)}</p>`));

  const modal = document.querySelector('#listing-modal'); const form = document.querySelector('#listing-form'); const photoInput = form.elements.photo; const preview = document.querySelector('#listing-image-preview'); const today = new Date().toISOString().slice(0, 10); form.elements.harvest_date.min = today; form.elements.pickup_ready_at.min = `${today}T00:00`; let photoData = '';
  document.querySelector('.auth-close').onclick = () => modal.classList.remove('open');
  photoInput.onchange = () => { const file = photoInput.files[0]; const error = document.querySelector('#listing-error'); if (!file) return; if (!['image/jpeg', 'image/png'].includes(file.type)) { photoInput.value = ''; error.textContent = 'Please choose a JPG or PNG image.'; return; } error.textContent = ''; preview.src = URL.createObjectURL(file); preview.hidden = false; const reader = new FileReader(); reader.onload = () => { photoData = reader.result; }; reader.readAsDataURL(file); };
  form.onsubmit = async event => { event.preventDefault(); const error = document.querySelector('#listing-error'); error.textContent = ''; if (!form.checkValidity() || !photoData) { error.textContent = 'Complete every required field and add a JPG or PNG image.'; form.reportValidity(); return; } const values = Object.fromEntries(new FormData(form)); if (values.harvest_date < today || values.pickup_ready_at.slice(0, 10) < today) { error.textContent = 'Harvest and pickup-ready dates cannot be in the past.'; return; } try { await api('/api/farmer/listings', { method: 'POST', body: JSON.stringify({ ...values, unit: 'kg', photo_url: photoData }) }); modal.classList.remove('open'); form.reset(); preview.hidden = true; photoData = ''; farmer(); } catch (issue) { error.textContent = issue.message; } };
}
